#!/bin/sh
set -e
case "$1" in
    configure)
    touch /etc/udev/rules.d/01-ryujin.rules
    echo "SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"0b05\", ATTRS{idProduct}==\"1aa2\", TAG+=\"uaccess\", MODE=\"0666\"" > /etc/udev/rules.d/01-ryujin.rules
    sudo udevadm control --reload-rules
    sudo udevadm trigger
    sudo mkdir /var/lib/ryujinIII
    sudo chmod 755 /var/lib/ryujinIII
    sudo touch /var/lib/ryujinIII/gif_array
    sudo touch /var/lib/ryujinIII/jpeg_array
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
