name: CMake on DEBIAN

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake build-essential git curl libusb-1.0-0 libusb-1.0-0-dev libargs-dev

      - name: Package project
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cd build
          cpack

      - name: Upload deb artifacts
        uses: actions/upload-artifact@v7
        with:
          path: build/*.deb
          archive: false

      - name: Upload targz artifacts
        uses: actions/upload-artifact@v7
        with:
          path: build/*.tar.gz
          archive: false

  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./*
          generate_release_notes: true